version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: ReConnect
      POSTGRES_USER: reconnect
      POSTGRES_PASSWORD: 1234
    ports:
      - "15432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    env_file:
      - environment.env     # 이원석 수정
    volumes:
      - ${USERPROFILE}/.m2:/root/.m2  # 이원석 수정
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MAVEN_OPTS: "-Dmaven.wagon.http.retryHandler.count=5 -Dsun.net.client.defaultConnectTimeout=120000 -Dsun.net.client.defaultReadTimeout=120000 -Dmaven.wagon.http.pool=false"
    container_name: springboot-app
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      TZ: Asia/Seoul
      APP_ENC_KEY: "a5fuR4bshAMWQwSy4zSKJNokjc7b3DA/SqIIOT9YC9o="
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/ReConnect
      SPRING_DATASOURCE_USERNAME: reconnect
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_SQL_INIT_MODE: never #이원석 수정

volumes:
  pgdata: