app:
  llm:
    api-key: ${API_KEY_FOR_LLM:dev_key}

spring:
  sql:
    init:
      mode: never         # 이원석 수정
      data-locations: classpath:data.sql   # 이원석 수정
logging:
  level: # 이원석 수정
    org.springframework.web: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: TRACE

management:
  endpoints:
    web:
      exposure:
        include: health,info