app:
  llm:
    api-key: ${API_KEY_FOR_LLM:dev_key}

spring:
  sql:
    init:
      mode: never         # 이원석 수정
      data-locations: classpath:data.sql   # 이원석 수정
logging:
  level: # 이원석 수정
    org.springframework.web: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: TRACE

fastapi:
  base-url: ${FASTAPI_BASE_URL:http://127.0.0.1:8000}  # 이부분이 주소들어가면돼용

management:
  endpoints:
    web:
      exposure:
        include: health,info