spring:
  datasource:
    url:
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        types:
          json: jsonb
    show-sql: true
  jackson:
    serialization:
      indent_output: true
